name: Testing

env:
  pythonDefaultValue: '3.8'
  clangppDefaultValue: '6.0'

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]
    paths-ignore:
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
  workflow_dispatch:

jobs:
  run-tests:
    name: run stan tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [env.pythonDefaultValue]
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules:  true
      - name: Run tests
        run: |
          echo "CXX=clang-${{ env.clangppDefaultValue }}" >> make/local
          echo "O=0" >> make/local
          python runTests.py -j 2 src/test/unit
