name: Testing

env:
  pythonDefaultValue: '3.8'
  clangppDefaultValue: '6.0'

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]
    paths-ignore:
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'

jobs:
  run-tests:
    name: run stan tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [env.pythonDefaultValue]
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules:  true
      - name: Install clang++
        run: sudo apt-get install clang-${{ env.clangppDefaultValue }}++
      - name: Run tests
        env:
          CXX: clang++-${{ env.clangppDefaultValue }}
        run: python runTests.py -j 2 src/test/unit
